version: '3.8'
services:
  postgres:
    container_name: pricewatch
    image: postgres:14.2
    restart: always
    environment:
      - POSTGRES_USER=damnstraight
      - POSTGRES_PASSWORD=damnstraight
      - POSTGRES_DB=pricewatch
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  postgres-test:
    container_name: pricewatch-test
    image: postgres:14.2
    restart: always
    environment:
      - POSTGRES_USER=damnstraight
      - POSTGRES_PASSWORD=damnstraight
      - POSTGRES_DB=pricewatch_test
    ports:
      - '5431:5432'
volumes:
  postgres: